### PR TITLE
Add PHP 8.4 support

### LINKED ISSUE #1450: Supports PHP 8.4
Even though PHP 8.4 hasn't been released yet, it would be nice to unlock the ability to upgrade to it.
I doubt there is any incompatibility.

### PR DESCRIPTION
**Pull request by hafezdivandari**
This is based on PR #1440 by @cedric-anne - Thank you Cédric!

~This PR also replaces `laminas/laminas-diactoros` with `nyholm/psr7` that supports PHP 8.4~
This PR also bumps some dev dependencies for PHP 8.4 tests to pass.

Fixes #1450

### CODE REVIEW

**Review by cedric-anne — APPROVED** [review]
:+1:

**Comment by Sephster** [comment]
Thank you @hafezdivandari and @cedric-anne for your work on this!

**Comment by crynobone** [comment]
@Sephster Can we have this release ASAP (as PHP 8.4 has been released)

**Comment by Sephster** [comment]
It hasn't yet. I will monitor and tag as soon as it is. I believe there is confusion here as the release has been tagged but my understanding is this does not equate to a release

**Comment by Sephster** [comment]
Has now been released so I'll get this out today :+1:

**Comment by hafezdivandari** [comment]
@Sephster Laravel Passport 12.x (current stable) supports oauth2-server 8.x, so we should eighter backport this PR for 8.x (#1459) or review /merge #1410 and #1420 to be able to release Passport 13.x with oauth2-server 9.x

**Comment by crynobone** [comment]
CleanShot 2024-11-21 at 20 24 40

This PR doesn't belong to any release. We can check it from the commit page. 

As an example, the following commit is available in `9.0.1`

CleanShot 2024-11-21 at 20 25 54

**Comment by crynobone** [comment]
@hafezdivandari Can we have v9 working on Passport 12?

**Comment by hafezdivandari** [comment]
@crynobone there are many BC breaking changes due to type declarations.

**Pull request merged**
