### PR TITLE
Added exception chaining in BearerTokenValidator

### PR DESCRIPTION
**Pull request by rhertogh**
Added exception chaining for RequiredConstraintsViolated in `\League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator::validateAuthorization()`.

This helps with logging the exception (similar to line 103).

### CODE REVIEW

**Review by sneakyvv — APPROVED** [review]
I was about to create the exact same PR, because I want to debug why the constraints are failing & which specifically.

**Comment by dungsaga** [comment]
oops, I created an identical PR (#1335) for this problem. We should either merge this or #1335.

**Comment by Sephster** [comment]
Thanks for the PR. I will merge this in tomorrow and close #1335 - thanks to both @rhertogh and @dungsaga

**Comment by dungsaga** [comment]
@Sephster let's merge this PR

**Comment by Sephster** [comment]
Merged. Many thanks to all that flagged or worked on this

**Pull request merged**
