### PR TITLE
Return Redirect URI in OAuthServerException

### PR DESCRIPTION
**Pull request by StephanMeijer**

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Fix needed, know doing workaround:

```
       $reflectionProperty = new ReflectionProperty(OAuthServerException::class, 'redirect_uri');
        $reflectionProperty->setAccessible(true);
        
        $uri = $reflectionProperty->getValue($e);
```

**Comment by Sephster** [comment]
Can you give a bit of detail about your scenario? Which grant do you need this for and in what context? Cheers!

**Comment by Sephster** [comment]
@StephanMeijer do you have some time to provide a bit of context for this change? Thanks for your help.

**Comment by StephanMeijer** [comment]
Yes @Sephster I will respond ASAP

**Comment by StephanMeijer** [comment]
@Sephster I used this to translate `OAuthServerException` to my custom class: `MedMijServerException`, which allows me to report and render the error using Laravel error handling.

**Comment by Sephster** [comment]
Thanks for the reply @StephanMeijer - could you detail why you needed to use a different exception class? Apologies for all the questions, I just want to understand what the current implementation is restricting you from doing. Thanks for your help

**Comment by StephanMeijer** [comment]
The use case I approached was a bit more complex. I had to create an OAuth service which does not strictly implement OAuth but was more stricter on specs from the government.

So I had to create custom error requests as well, where redirects were required.

**Comment by Sephster** [comment]
Thanks @StephanMeijer - can't think of a reason not to expose this so have merged. Cheers

**Comment by StephanMeijer** [comment]
Thanks for your help

**Pull request merged**
