### PR TITLE
Fix PHP 8.4 deprecation notices

### PR DESCRIPTION
**Pull request by Hlavtox**
- Fixes PHP 8.4 deprecation notices.
- See https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

Is it possible to do a patch release on 8.x branch after merge? :-) Thanks!

### CODE REVIEW

**Comment by crynobone** [comment]
Maybe we should update styleci.yml and automate the fixes

**Comment by crynobone** [comment]
```diff
preset: psr12

risky: true

enabled:
  - blank_line_before_return
  - fully_qualified_strict_types
  - hash_to_slash_comment
  - include
  - method_separation
  - native_function_casing
  - no_blank_lines_between_uses
  - no_duplicate_semicolons
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_singleline_array
  - no_unused_imports
  - no_whitespace_before_comma_in_array
+ - nullable_type_declarations
  - ordered_imports
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_simplified_null_return
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - print_to_echo
  - short_array_syntax
  - single_quote
  - spaces_cast
  - standardize_not_equal
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - whitespace_after_comma_in_array
```

**Comment by jolelievre** [comment]
Hi @Sephster 

we have a dependency on your repository at https://github.com/PrestaShop/PrestaShop that is what motivated this contribution.
But I guess we can try and upgrade to your v9 once the patch for PHP 8.4 is released indeed 😉

Just to anticipate the timing, do you think the next patch that includes this compatibility will be released soon or will we have to wait a few weeks or more?

**Comment by Hlavtox** [comment]
Hi @Sephster, I added the config to the linter. :-)

Yes, as @jolelievre said, we wanted to avoid as many major updates as we can. Get it working, stabilized, then get on the major updates if we have time.

**Comment by jolelievre** [comment]
Yep, anyway it may still be useful for other projects

**Comment by Sephster** [comment]
Happy to merge this but currently failing because of dependencies. Are you able to fix this? If not, I'll see if I can get some time later today. Thank you and thanks for letting me know about PrestaShop. Always nice to hear about down stream systems! Looks a great product

**Comment by hafezdivandari** [comment]
The `roave/security-advisories` doesn't allow old `laminas/laminas-diactoros` versions, and newer versions of `laminas/laminas-diactoros` doesn't support PHP 7.x. The only way to fix the failing checks is to replace `laminas/laminas-diactoros` with `nyholm/psr7`. Let me know if this is what you want. Check this commit: https://github.com/thephpleague/oauth2-server/pull/1454/commits/fce9b7456e0b16b2496cf01c02fa6eded3e7a7f1

**Comment by crynobone** [comment]
We can also consider removing `roave/security-advisories` on GitHub Actions for PHP 7.x (since it already out of security patches as well).

```diff
+     - name: Remove Security Advisories on obsolete PHP versions
+       run: composer remove "roave/security-advisories" --dev --no-update
+.      if: matrix.php <= 7.4

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

**Comment by wmouwen** [comment]
> @Hlavtox is there something blocking you from upgrading to 9?

@Sephster There is: #1456.

The broken client credentials grant for the Symfony bundle prevents us from upgrading to v9. Upgrading to PHP 8.4 on v8 starts throwing deprecation warnings. Targeting v8 or backporting would help anyone using `league/oauth2-server-bundle` to move forward with the PHP version without these warnings all over.

Best way forward would be to have #1456 sorted out, though. That way the Symfony userbase can upgrade to v9 too.

**Comment by crynobone** [comment]
@Hlavtox are you able to continue working on this?

**Comment by Hlavtox** [comment]
Hi guys, sorry, but I will close it for now. We upgraded to v9 eventually. 👍

**Pull request closed without merging**
