### PR TITLE
spec compliant 'error_description' but keep 'message' for BC

### PR DESCRIPTION
**Pull request by marc-mabe**
see #958 

This is only fixing one part of the problem explained in #958.
I think the other problem with missing `state` parameter should be done separately.

### CODE REVIEW

**Comment by Sephster** [comment]
Thanks @marc-mabe - although the duplication isn't ideal it is a way forwards without introducing a breaking change in the version 7 branch. Happy to merge this in. 

Will look to make a full change to use `error_description` in version 8.

**Comment by Sephster** [comment]
@marc-mabe I was going to create a release for this but I'm now thinking this isn't required.

The `error_description` is applicable for authorization requests from the implicit grant and auth code grant.

At the moment I think we do need to have a way to optionally specify the `error_description` but if we want to make this spec compliant, I don't think moving to replace the existing `message` is the way to go about this.

On the surface, it looked like someone had put the property in as a wrong name but on closer inspection, I think this is something custom to this library to assist developers.

I would appreciate your thoughts on this but given this, I will likely revert this PR.

**Comment by driesvints** [comment]
This seems to have broken the Passport build but I can see that this isn't a breaking change so we should just fix our build for this: https://travis-ci.org/laravel/passport/builds/519352496

**Comment by Sephster** [comment]
Thanks @driesvints - sorry this caused you issues. We made every effort to ensure it didn't break functionality but looks like this did break your test. I will try and remember to check changes like this against Passport in future and be proactive with a fix.

**Comment by driesvints** [comment]
No worries at all. I don't consider this to be a breaking change. In the end it only broke our test suite because we're doing some a pretty aggressive assertion there. It's probably better if we used a "contains" assertion instead.

**Pull request merged**
