### PR TITLE
Version 5

### PR DESCRIPTION
**Pull request by alexbilbie**
Version 5 is a major rewrite.

* [x] JWT support
* [x] PSR-7 support
* [x] Improved exception errors
* [x] Replace all occurrences of the term "Storage" with "Repository"
* [x] Simplify repositories
* [x] Entities conform to interfaces and use traits
* [x] Auth code grant updated
    * [x] Allow support for public clients
    * [x] Add support for #439
* [x] Client credentials grant updated
* [x] Password grant updated
    * [x] Allow support for public clients
* [x] Refresh token grant updated
* [x] Implement Implicit grant
* [x] Bearer token output type
* [x] Remove MAC token output type
* [x] Authorization server rewrite
* [x] Resource server class moved to PSR-7 middleware
* [x] Tests
* [x] V5 docs

### CODE REVIEW

**Comment by vinkla** [comment]
Great work @alexbilbie! Could you let us know about when this is closing its merge state? Then @lucadegasperi and I can start working on the next version of the Laravel wrapper package. We don't want to start to early with the Laravel package if there will be any major changes happening in version 5. Please let us know. Thanks.

**Comment by alexbilbie** [comment]
Will do. At the pace I'm going at (have found myself with a lot more time this side of Christmas) I reckon another week.

If my plan works out then implementations will only need one DB table for token storage + optional tables if you want DB driven scopes + clients :smile:

**Comment by vinkla** [comment]
Sounds good!

**Comment by juliangut** [comment]
Maybe this is my personal preference but I find `ResponseTypes` to be misleading, they are not Response objects of any type. I'd rename it to something related tokens, `ResponseToken`, `TokenType` ...

**Comment by juliangut** [comment]
How is it going with V5 @alexbilbie ?

**Comment by paragonie-scott** [comment]
https://github.com/thephpleague/oauth2-server/blob/V5-WIP/src/CryptTrait.php#L74 needs to use the same padding mode as decryption

**Comment by frederikbosch** [comment]
@alexbilbie Would you mind releasing a first alpha of version 5? Or do you have other plans on releasing?

**Comment by alexbilbie** [comment]
So the plan is to get a release candidate with new docs out in the next few
days. I'm then away from the 25th of March for two weeks without access to
a computer. When I'm back any outstanding issues will be resolved and V5
will formally be released.

Thanks for your patience everyone; it's been a long time coming but we're
on the final straight now and I really do think this is the best
implementation to date.

**Comment by entwu** [comment]
@alexbilbie Perfect! I have been waiting for V5 a while. I want to rewrite repository layer to use redis but there was this session concept on the way... 
btw. you did rly good job on the package !

**Comment by alexbilbie** [comment]
:tada: :tada: :tada: :tada: :tada: I've tagged and published `5.0.0-RC1` :tada: :tada: :tada: :tada: :tada:

I'd like to thank everyone for supporting me this far.

I'm away for two weeks from tomorrow which gives plenty of time for people to try it out. V5 is very stable, has a full suite of tests and working examples. 

I've completely rewritten all of the documentation too - http://oauth2.thephpleague.com/ - every page even has content, not a `@todo` in sight :stuck_out_tongue:

I'm going to have limited access to emails over the next few weeks but please feel free to open issues and PRs and I will review as soon as I'm home :+1:

**Comment by frederikbosch** [comment]
Great, thanks for your work @alexbilbie!

**Comment by tjboudreaux** [comment]
@alexbilbie thank you so much for this.  I started using this branch a few weeks ago to get a head start on implementing JWT support in a project I'm working on and it's worked really well for me so far.

**Comment by alexbilbie** [comment]
Version 5 has now been released!

Thank you to everyone for your support!

**Pull request merged**
