### PR TITLE
Removed lcobucci/jwt deprecations from Builder

### PR DESCRIPTION
**Pull request by DonCallisto**

### CODE REVIEW

**Comment by Sephster** [comment]
This looks great. I will merge this in later today once I've had time to update the changelog but looks good to me. Thanks for spotting this and updating.

**Comment by DonCallisto** [comment]
@Sephster I've also modified the changelog file.

**Comment by Sephster** [comment]
Thanks for this @DonCallisto - I moved the changelog message to the changed heading instead but otherwise looks great. Thanks for your efforts with this. Very much appreciated. Happy to merge.

**Comment by DonCallisto** [comment]
Thanks for reviewing and merging this quickly.
If there's anything you need help with just let me know as in these weeks I have more free time than ever so I'm speding a couple of hours a day in OSS.

**Pull request merged**
