### PR TITLE
Replace deprecated package

### PR DESCRIPTION
**Pull request by JC5**
The Zend package is deprecated. Replaced it with the new one. According to the docs, the package are the same except for the name.

- https://github.com/laminas/laminas-diactoros
- https://github.com/zendframework/zend-diactoros

### CODE REVIEW

**Comment by mfn** [comment]
Interesting, because the namespace also changed. Why does it still work? 😄

**Comment by JC5** [comment]
It's still on [Packagist](https://packagist.org/packages/zendframework/zend-diactoros), so I guess that's why :)

**Comment by mfn** [comment]
No, sorry I meant the laminas/laminas-diactoros package uses a different namespace but other changes required?

https://github.com/laminas/laminas-diactoros/blob/master/src/Response.php#L11
image

**Comment by JC5** [comment]
Oh lol I didn't notice it. I checked the readme and they claimed it was just a new package. Sorry, this PR could then best be closed I guess.

**Comment by Sephster** [comment]
@JC5 thanks for this. Are you able to update the relevant namespaces and update the readme accordingly? Thanks for spotting this.

**Comment by JC5** [comment]
Done. StyleCI complains about sorting, but that seems to be it.

**Comment by Sephster** [comment]
Thanks @JC5

**Comment by JC5** [comment]
:+1:

**Pull request merged**
