### PR TITLE
Allow CryptTrait to accept a \Defuse\Crypto\Key as encryption key #812

### PR DESCRIPTION
**Pull request by SunMar**
See #812 for details. This allows a Key object to be used as encryption key over an alphanumeric string which improves performance of encryption and decryption.

### CODE REVIEW

**Comment by SunMar** [comment]
@Sephster Ah yes, sorry, forgot about those interfaces. Phpdoc updates.

**Comment by SunMar** [comment]
I also updated the PR to remove some code duplication in the `CryptTraitTest`.

**Comment by SunMar** [comment]
@simonhamp `setEncryptionKey()` is called by `AuthorizationServer` and is basically a pass-through for whatever encryption key is passed when doing a `new AuthorizationServer`, which is done by whoever is implementing this package and is not done by the package itself.

So I'm not really sure how to get rid of the `if`, because the library doesn't have control over whether the encryption is a `string` or a `Key`. This way it stays backwards compatible, if you pass a `string` it does the current implementation of `encryptWithPassword()` and only if you pass a `Key` it uses `encrypt()`.

Note that in the tests `doEncrypt()` and `doDecrypt()` are just pass-throughs in the stub to `encrypt()` and `decrypt()` because they are `protected` and can't be called directly. See [CryptTraitStub](https://github.com/thephpleague/oauth2-server/blob/8c93fd74c9efa2d81b20dc150bf278f6f62094c0/tests/Stubs/CryptTraitStub.php#L21).

**Comment by SunMar** [comment]
@Sephster Is the PR ok for you too? I updated the change you requested.

**Comment by Sephster** [comment]
Sorry for the delay in getting this reviewed @SunMar. I've made some minor changes but all looks good so merging in. Thanks for your patience and your contribution

**Pull request merged**
