### PR TITLE
Rename phpunit.xml file

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by alexbilbie** [comment]
Why?

**Comment by vinkla** [comment]
This will allow developers to keep a custom phpunit.xml for development.

**Comment by alexbilbie** [comment]
As it's such a barebones `phpunit.xml` file in the first place I'm not against others adding to it in a PR if they have useful improvements

**Comment by vinkla** [comment]
It is just a way to let developers customize the settings in their local environment. It is common to use .dist(ribution) when pushing packages to GitHub. Nothing important really :) Just a best practice.

**Comment by GawainLynch** [comment]
Just a note in support of this PR. PHPUnit will check for the `.xml.dist` file if the `.xml` isn't present, so there is no negative impact on the project… but it can make short term testing changes a lot easier for a developer.

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
