### PR TITLE
V5 - use phpseclib for encryption/decryption

### PR DESCRIPTION
**Pull request by juliangut**
Make use of [phpseclib](https://github.com/phpseclib/phpseclib/tree/2.0) for encryption/decryption of refresh tokens payload, it allows to change algorithm (symmetric/asymmetric) if needed, using RSA by default

### CODE REVIEW

**Comment by alexbilbie** [comment]
How does this work if the key has a password?

**Comment by juliangut** [comment]
You've come to a good point! This line is needed in decrypt method
```php
self::getAlgorithm()->setPassword($privateKeyPassword);
```
It adds an extra parameter to be handled in case RSA key has a password

It's added logic but I "guess" the benefits of being able to switch algos outruns the drawbacks of having to store and pass an extra parameter, maybe??

**Comment by juliangut** [comment]
Added `privateKeyPassword` parameter.

Parameters on `Server::__construct` and `AbstractResponseType::__construct` needed reordering to allow default empty string for privateKeyPassword

**Comment by juliangut** [comment]
I'm not very fond of this, should probably rewrite this completely. Anyway my goal is to avoid "Helper" classes such as KeyCrypt, IMO such functionality belong in a Trait

**Comment by juliangut** [comment]
Dropping in favor of #468

**Pull request closed without merging**
