### PR TITLE
Validate expected type of input parameter

### LINKED ISSUE #1209: TypeError in mallformed tokens
I'm using https://github.com/mezzio/mezzio-authentication-oauth2 and noticed thousands of 500 errors on our server.
(Someone tried to access something he should not but I don't expect this bug a security issue.)

The problem happens if someone passes a token not as string.

E.g:
```php
        $data = [
            'grant_type'    => 'refresh_token',
            'refresh_token' => ['not', 'a', 'string'],
            'client_id'     => $ssoClient['client_id'],
            'client_secret' => $ssoClient['client_secret'],
        ];
        $I->sendPOST('/oauth2/token', $data);
        $I->seeResponseCodeIs(401);
```
```
TypeError raised in file /app/vendor/defuse/php-encryption/src/Crypto.php line 136:
Message: String expected for argument 1. Array given instead.
Stack Trace:
#0 /app/vendor/league/oauth2-server/src/CryptTrait.php(69): Defuse\Crypto\Crypto::decryptWithPassword(Array, '/app/config/aut...')
#1 /app/vendor/league/oauth2-server/src/Grant/RefreshTokenGrant.php(107): League\OAuth2\Server\Grant\AbstractGrant->decrypt(Array)
#2 /app/vendor/league/oauth2-server/src/Grant/RefreshTokenGrant.php(47): League\OAuth2\Server\Grant\RefreshTokenGrant->validateOldRefreshToken(Object(Laminas\Diactoros\ServerRequest), 'accounts.fronte...')
#3 /app/vendor/league/oauth2-server/src/AuthorizationServer.php(198): League\OAuth2\Server\Grant\RefreshTokenGrant->respondToAccessTokenRequest(Object(Laminas\Diactoros\ServerRequest), Object(League\OAuth2\Server\ResponseTypes\BearerTokenResponse), Object(DateInterval))
#4 /app/vendor/mezzio/mezzio-authentication-oauth2/src/TokenEndpointHandler.php(71): League\OAuth2\Server\AuthorizationServer->respondToAccessTokenRequest(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Diactoros\Response))
```

The bug seems to be fixed with but other grant types are very likely effected, too
```php
        if (!\is_string($encryptedRefreshToken)) {
            throw OAuthServerException::invalidRefreshToken('Refresh token mallformed');
        }
```

### PR DESCRIPTION
**Pull request by marc-mabe**
fixes #1209

### CODE REVIEW

**Comment by marc-mabe** [comment]
Any update on this? Do you need something from me?

**Comment by Sephster** [comment]
Thanks @marc-mabe - looks good. We could maybe change this at a later date to have a generic catching of `Error` classes but this looks to solve the issue at hand. Thanks for submitting this.

**Comment by Sephster** [comment]
I honestly didn't think this would have caused any breaking change. Sorry that this happened for you. The username is retrieved from the request using the `getRequestParameter()` function which returns either a string or null if the value isn't present. This function is calling the `getParsedBody()` function from the HTTP Request wrapper. As far as I can tell, this should always return a key value pair of string => string so I didn't think this would cause any issue. 

Were you already changing the value to be an int somewhere? Sorry again for any inconvenience caused

**Comment by JorgenSolli** [comment]
No need to apologize. Shit happens 😄 

I didn't dig too deep here, but I can share some code if you're interested in what exactly happened.
Note that this is using Laravel (v8) and its Passport (v10) package, which depends on this package.

My implementation looks like this:
```
$data = [
    'grant_type' => 'password',
    'client_id' => $request->get('client_id'),
    'client_secret' => $request->get('client_secret'),
    'username' => "$user->id", // Needs to be a string lol
    'password' => $request->get('password'),
];

try {
    $loginRequest = Request::create('/oauth/token', 'POST', $data, [], [], $server);
    $loginRequest->headers->set('host', $request->getHttpHost());
    $response = app()->handle($loginRequest);
} ...
```
This implementation is somewhat unorthodox, I know.

The stacktrace:
```
[previous exception] [object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 3): The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. at /application/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:142)
[stacktrace]
#0 /application/vendor/league/oauth2-server/src/Grant/PasswordGrant.php(90): League\\OAuth2\\Server\\Exception\\OAuthServerException::invalidRequest('username')
#1 /application/vendor/league/oauth2-server/src/Grant/PasswordGrant.php(56): League\\OAuth2\\Server\\Grant\\PasswordGrant->validateUser(Object(Nyholm\\Psr7\\ServerRequest), Object(Laravel\\Passport\\Bridge\\Client))
#2 /application/vendor/league/oauth2-server/src/AuthorizationServer.php(204): League\\OAuth2\\Server\\Grant\\PasswordGrant->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse), Object(DateInterval))
#3 /application/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(65): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(Nyholm\\Psr7\\Response))
#4 /application/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(24): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->Laravel\\Passport\\Http\\Controllers\\{closure}()
```

Not sure if this helps you understand what and why this happened, but this is what I managed to scrape together before bedtime.

**Pull request merged**
