### PR TITLE
Fixing permission error

### PR DESCRIPTION
**Pull request by pradeep5485**

### CODE REVIEW

**Comment by parallels999** [comment]
`.DS_Store` ??
#1383

**Comment by eugene-borovov** [comment]
This change is wrong. Private key may have readonly permission (400 or 440).

**Comment by Sephster** [comment]
Aye it doesn't seem right. Will wait a few days for the author to give an explanation in case we've missed something but I think this isn't fixing anything

**Comment by Sephster** [comment]
Closing as no response from author

**Pull request closed without merging**
