### PR TITLE
Update auth-server-auth-code.md

### PR DESCRIPTION
**Pull request by bobmulder**
Guess this is not the Authorization Server ;) Didn't know how to call it so I named it to 'client callback'.

### CODE REVIEW

**Comment by bobmulder** [comment]
Wow, made a mistake there ;P haha sorry!

**Comment by alexbilbie** [comment]
You've found a mistake in the docs; could you change it to:

"If the user approves the client they will be redirected from the authorisation server to the client's redirect URI with the following parameters in the query string:"

**Comment by bobmulder** [comment]
Are you sure it was a mistake @alexbilbie? I am trying to implement the Authorization Code Grant right now, but I really struggle at this point...

**Comment by alexbilbie** [comment]
Yes, once the user has authorised the client they are redirect back to the client with the authorisation code which is exchanged for an access token. Your PR is correct

**Comment by bobmulder** [comment]
Pfew :)

**Pull request merged**
