### PR TITLE
Allow random compat 2.x

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Indeed would be nice to have so it can be installed on Laravel 5.3.

**Comment by alexbilbie** [comment]
Will include this in the next tag release

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by alexbilbie** [comment]
5.1.0 has been released

**Comment by GrahamCampbell** [comment]
Awesome.

**Pull request merged**
